/**
 * Codified model-contract constants — the bytes-locked strings the model
 * sees in every spawn's prompt and in every pool's shared spine prefix.
 *
 * These five exports are the entire shape of the HDK 3.0 model contract.
 * Every byte the model encounters in framework-controlled prompt content
 * traces back to one of these constants (or to grammar-sanitized
 * `app.json` metadata interpolated through them).
 *
 * Lifted verbatim from production (`reasoning.run/src/prompts/playbooks.eta`,
 * `web-worker.eta`, `corpus-worker.eta`) with one substitution:
 * `playbook` → `contract` at the noun position. See RFC §1.7 and the
 * Architectural reference section for the rationale.
 *
 * **Do not duplicate these literals anywhere else.** `renderSpine` and
 * `renderAgentPreamble` reference these constants by name. Changing the
 * codified contract is one edit here plus a §10.3 trace-gate re-run; the
 * framework's internal call graph does not need touching.
 *
 * @packageDocumentation
 * @category Contract
 */

/**
 * Boundary marker prepended to every per-spawn user-role message — RFC §1.1.
 *
 * Exact rendered shape: `Apply the **<name>** contract.\n\n`
 * (marker line + blank line). The `<name>` comes from
 * `app.manifest.contract.name`, grammar-sanitized to
 * `[a-z][a-z0-9_-]{1,63}` at `defineApp` time (§3.2 M3) so it cannot break
 * the markdown bold or inject newlines.
 *
 * Framework-prepended by `renderAgentPreamble`. App `agent.eta` source
 * MUST NOT contain the literal `Apply the **` substring — `defineApp`
 * rejects sources that do.
 */
export const BOUNDARY_MARKER = (name: string): string =>
  `Apply the **${name}** contract.\n\n`;

/**
 * Framework intro paragraph emitted at the start of every spine — RFC §1.3.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:1`, with
 * `playbook` → `contract` substituted (three occurrences inside the
 * sentence). Followed at render time by a blank line + `# Contracts`
 * header + the per-app catalog entries (§1.2).
 */
export const FRAMEWORK_INTRO =
  'You are an assistant working as part of a multi-agent workflow. ' +
  'You have access to the tools below, grouped by contract. ' +
  'You should only use the tools for a given contract when that particular ' +
  'contract is requested explicitly in your task instructions.';

/**
 * Tool-selection rule emitted after all per-app catalog entries — RFC §1.4.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:17-19` with
 * `playbook` → `contract` substituted and the trailing `palette` →
 * `tools` (palette was retired from the framework vocabulary — see
 * Architectural reference). This is the abstract invariant the model
 * routes against; concrete cross-contract BAD examples are NOT
 * generated by the framework — the abstract rule + dispatch-time
 * scope-guard carry the discipline (RFC §3.2 M2).
 */
export const TOOL_SELECTION_RULE =
  '# Tool selection rule\n\n' +
  'The agent system message will tell you which contract to apply. ' +
  "Use only that contract's tools. " +
  'The agent system message also carries an engineered PROCESS that dictates ' +
  'intra-contract ordering. ' +
  "Follow that PROCESS, but constrained to the assigned contract's tools.";

/**
 * Per-app catalog entry shape emitted under the `# Contracts` header — RFC §1.2.
 *
 * Exact rendered shape (three lines + trailing blank line):
 * ```
 * ## <name>
 * Tools: <t1>, <t2>, ...
 * Use when: <useWhen>
 *
 * ```
 *
 * `name` is grammar-sanitized at `defineApp` time. `tools` is the
 * `contract.tools` array joined with `, `. `useWhen` is grammar-constrained
 * to a single sentence of printable characters with no chat-role markers,
 * no markdown code fences, no newlines (§3.2 M3).
 */
export const CATALOG_ENTRY = (
  name: string,
  tools: readonly string[],
  useWhen: string,
): string =>
  `## ${name}\nTools: ${tools.join(', ')}\nUse when: ${useWhen}\n`;

// ── Model fleet ───────────────────────────────────────────────────

/**
 * Model family entry in {@link VALIDATED_MODELS_3_0}.
 */
export interface ValidatedModelFamily {
  /** Model family identifier (e.g., `'qwen3'`, `'llama-3'`). */
  family: string;
  /**
   * Validated revisions of the family. `['*']` means all revisions of
   * the family pass; specific revision strings (e.g., `['3.5']`) restrict
   * to a subset.
   */
  revisions: readonly string[];
}

/**
 * Model families against which the HDK 3.0 model contract has been
 * validated via production traces — RFC §1.5.
 *
 * Off-fleet models are unvalidated: the boundary marker, catalog format,
 * and tool-selection rule have not been verified to elicit correct
 * routing. Consumers running off-fleet models get best-effort routing —
 * the contract may degrade silently. The framework does not gate on the
 * running model's family; HDK is model-agnostic by design.
 *
 * Extending the fleet for a new family requires re-running the
 * verification gates (RFC §10) against that family and updating this
 * constant. `modelContractVersion` does NOT bump for fleet expansion —
 * only for changes to the marker, catalog format, or tool-selection
 * rule that require re-validation across all listed families.
 */
export const VALIDATED_MODELS_3_0: readonly ValidatedModelFamily[] = [
  { family: 'qwen3', revisions: ['*'] },
  { family: 'qwen3.5', revisions: ['*'] },
  { family: 'llama-3', revisions: ['*'] },
  { family: 'phi-3.5', revisions: ['*'] },
  { family: 'gemma-3', revisions: ['*'] },
];

/**
 * The model contract version this build of `@lloyal-labs/rig` ships.
 *
 * Apps declare `modelContractVersion` in `app.json`; `defineApp` and the
 * registry (`createAppRegistry({ apps })` / `registry.enable`) refuse to
 * enable apps whose declared version is not in
 * {@link SUPPORTED_MODEL_CONTRACT_VERSIONS}. Per RFC §1.6.
 */
export const MODEL_CONTRACT_VERSION = '3.0';

/**
 * The set of model-contract versions this build of `@lloyal-labs/rig`
 * accepts at app-registration time. Within rig 3.x the only valid value
 * is `'3.0'`. A 4.0 contract would require re-validation across every
 * family in {@link VALIDATED_MODELS_3_0}. Framework semver (rig 3.0 →
 * 3.1) does NOT bump the model contract; that's the point of the
 * separate version line.
 */
export const SUPPORTED_MODEL_CONTRACT_VERSIONS: readonly string[] = ['3.0'];
